kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: flink
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 40443
        protocol: TCP
      - containerPort: 30980
        hostPort: 40080
        protocol: TCP
      - containerPort: 6123
        hostPort: 46123
        protocol: TCP
      - containerPort: 6124
        hostPort: 46124
        protocol: TCP
  - role: worker
  - role: worker

networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
